// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Seth Lawler",
            "email": "slawler@dewberry.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "[LandingPage Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_landing_page)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Landing Page",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/conformance": {
            "get": {
                "description": "[Conformance Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_conformance_classes)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "API Conformance List",
                "responses": {
                    "200": {
                        "description": "conformsTo:[\"http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/....\"]",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "[Job List Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_job_results)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Summary of all (active) Jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/jobs.JobRecord"
                            }
                        }
                    }
                }
            }
        },
        "/jobs/{jobID}": {
            "get": {
                "description": "[xxx Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_status_info)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Job Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.jobResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "[Dismss Job Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#ats_dismiss)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Dismiss Job",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.jobResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{jobID}/logs": {
            "get": {
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Job Logs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jobs.JobLogs"
                        }
                    }
                }
            }
        },
        "/jobs/{jobID}/results": {
            "get": {
                "description": "[Job Results Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_job_results)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Job Results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.jobResponse"
                        }
                    }
                }
            }
        },
        "/processes": {
            "get": {
                "description": "[Process List Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_list)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "processes"
                ],
                "summary": "List Available Processes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/processes/{processID}": {
            "get": {
                "description": "[Process Description Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_description)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "processes"
                ],
                "summary": "Describe Process Information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "processID",
                        "name": "processID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/processes.processDescription"
                        }
                    }
                }
            }
        },
        "/processes/{processID}/execution": {
            "post": {
                "description": "[Execute Process Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_create_job)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "processes"
                ],
                "summary": "Execute Process",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.jobResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.jobResponse": {
            "type": "object",
            "properties": {
                "jobID": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "outputs": {},
                "processID": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "default": "process"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "jobs.JobLogs": {
            "type": "object",
            "properties": {
                "api_logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "container_logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "jobID": {
                    "type": "string"
                }
            }
        },
        "jobs.JobRecord": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "jobID": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "processID": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "default": "process"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "processes.Info": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jobControlOptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "outputTransmission": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "processes.Input": {
            "type": "object",
            "properties": {
                "literalDataDomain": {
                    "$ref": "#/definitions/processes.LiteralDataDomain"
                }
            }
        },
        "processes.Inputs": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "input": {
                    "$ref": "#/definitions/processes.Input"
                },
                "maxOccurs": {
                    "type": "integer"
                },
                "minOccurs": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "processes.Link": {
            "type": "object",
            "properties": {
                "href": {
                    "type": "string"
                },
                "rel": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "processes.LiteralDataDomain": {
            "type": "object",
            "properties": {
                "dataType": {
                    "type": "string"
                },
                "valueDefinition": {
                    "$ref": "#/definitions/processes.ValueDefinition"
                }
            }
        },
        "processes.Output": {
            "type": "object",
            "properties": {
                "formats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "processes.Outputs": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "inputID": {
                    "description": "json omit",
                    "type": "string"
                },
                "output": {
                    "$ref": "#/definitions/processes.Output"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "processes.Resources": {
            "type": "object",
            "properties": {
                "cpus": {
                    "type": "number"
                },
                "memory": {
                    "type": "integer"
                }
            }
        },
        "processes.ValueDefinition": {
            "type": "object",
            "properties": {
                "anyValue": {
                    "type": "boolean"
                },
                "possibleValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "processes.processDescription": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                },
                "info": {
                    "$ref": "#/definitions/processes.Info"
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/processes.Inputs"
                    }
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/processes.Link"
                    }
                },
                "maxResources": {
                    "$ref": "#/definitions/processes.Resources"
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/processes.Outputs"
                    }
                }
            }
        }
    },
    "externalDocs": {
        "description": "Schemas",
        "url": "http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "dev-4.19.23",
	Host:             "localhost:5050",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Process-API Server",
	Description:      "An OGC compliant process server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
