basePath: /
definitions:
  handlers.jobResponse:
    properties:
      jobID:
        type: string
      message:
        type: string
      outputs: {}
      processID:
        type: string
      status:
        type: string
      type:
        default: process
        type: string
      updated:
        type: string
    type: object
  jobs.JobLogs:
    properties:
      api_logs:
        items:
          type: string
        type: array
      container_logs:
        items:
          type: string
        type: array
      jobID:
        type: string
    type: object
  jobs.JobRecord:
    properties:
      host:
        type: string
      jobID:
        type: string
      mode:
        type: string
      processID:
        type: string
      status:
        type: string
      type:
        default: process
        type: string
      updated:
        type: string
    type: object
  processes.Info:
    properties:
      description:
        type: string
      id:
        type: string
      jobControlOptions:
        items:
          type: string
        type: array
      outputTransmission:
        items:
          type: string
        type: array
      title:
        type: string
      version:
        type: string
    type: object
  processes.Input:
    properties:
      literalDataDomain:
        $ref: '#/definitions/processes.LiteralDataDomain'
    type: object
  processes.Inputs:
    properties:
      id:
        type: string
      input:
        $ref: '#/definitions/processes.Input'
      maxOccurs:
        type: integer
      minOccurs:
        type: integer
      title:
        type: string
    type: object
  processes.Link:
    properties:
      href:
        type: string
      rel:
        type: string
      title:
        type: string
      type:
        type: string
    type: object
  processes.LiteralDataDomain:
    properties:
      dataType:
        type: string
      valueDefinition:
        $ref: '#/definitions/processes.ValueDefinition'
    type: object
  processes.Output:
    properties:
      formats:
        items:
          type: string
        type: array
    type: object
  processes.Outputs:
    properties:
      id:
        type: string
      inputID:
        description: json omit
        type: string
      output:
        $ref: '#/definitions/processes.Output'
      title:
        type: string
    type: object
  processes.Resources:
    properties:
      cpus:
        type: number
      memory:
        type: integer
    type: object
  processes.ValueDefinition:
    properties:
      anyValue:
        type: boolean
      possibleValues:
        items:
          type: string
        type: array
    type: object
  processes.processDescription:
    properties:
      image:
        type: string
      info:
        $ref: '#/definitions/processes.Info'
      inputs:
        items:
          $ref: '#/definitions/processes.Inputs'
        type: array
      links:
        items:
          $ref: '#/definitions/processes.Link'
        type: array
      maxResources:
        $ref: '#/definitions/processes.Resources'
      outputs:
        items:
          $ref: '#/definitions/processes.Outputs'
        type: array
    type: object
host: localhost:5050
info:
  contact:
    email: slawler@dewberry.com
    name: Seth Lawler
  description: An OGC compliant process server.
  title: Process-API Server
  version: dev-4.19.23
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: '[LandingPage Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_landing_page)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Landing Page
      tags:
      - info
  /conformance:
    get:
      consumes:
      - '*/*'
      description: '[Conformance Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_conformance_classes)'
      produces:
      - application/json
      responses:
        "200":
          description: conformsTo:["http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/...."]
          schema:
            additionalProperties: true
            type: object
      summary: API Conformance List
      tags:
      - info
  /jobs:
    get:
      consumes:
      - '*/*'
      description: '[Job List Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_job_results)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/jobs.JobRecord'
            type: array
      summary: Summary of all (active) Jobs
      tags:
      - jobs
  /jobs/{jobID}:
    delete:
      consumes:
      - '*/*'
      description: '[Dismss Job Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#ats_dismiss)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.jobResponse'
      summary: Dismiss Job
      tags:
      - jobs
    get:
      consumes:
      - '*/*'
      description: '[xxx Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_status_info)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.jobResponse'
      summary: Job Status
      tags:
      - jobs
  /jobs/{jobID}/logs:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs.JobLogs'
      summary: Job Logs
      tags:
      - jobs
  /jobs/{jobID}/results:
    get:
      consumes:
      - '*/*'
      description: '[Job Results Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_job_results)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.jobResponse'
      summary: Job Results
      tags:
      - jobs
  /processes:
    get:
      consumes:
      - '*/*'
      description: '[Process List Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_list)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: List Available Processes
      tags:
      - processes
  /processes/{processID}:
    get:
      consumes:
      - '*/*'
      description: '[Process Description Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_description)'
      parameters:
      - description: processID
        in: path
        name: processID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/processes.processDescription'
      summary: Describe Process Information
      tags:
      - processes
  /processes/{processID}/execution:
    post:
      consumes:
      - '*/*'
      description: '[Execute Process Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_create_job)'
      parameters:
      - description: pyecho
        in: path
        name: processID
        required: true
        type: string
      - description: '{'
        in: body
        name: input
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.jobResponse'
      summary: Execute Process
      tags:
      - processes
schemes:
- http
swagger: "2.0"
