@startuml dismiss
!theme mars

title Job Dismiss Request Flow
header
    For simplicity, this diagram is created for an async job running on a cloud platform.
    Jobs with different configurations have "almost" identical sequences.
end header

participant User
participant Server
entity Job
participant "Execution\nPlatform"
participant Storage

User -> Server: Submit async job
activate Server

Server -> Job: Create new job with Job ID
activate Job
Job -> "Execution\nPlatform": Register Job
activate "Execution\nPlatform"

Job --> Server: Return acknowledgment
Server --> User: Respond with 201 and Job ID
deactivate Server

User -> Server: Request dismiss for a job
activate Server
Server -> Job: Check if job is active
Job --> Server: Job is active
Server -> Job: Kill job
Job -> "Execution\nPlatform": Kill job
Job -> Job: Update job status\nto `dismissed`
Job --> Server: Job dismissed
Server --> User: Job dismissed
deactivate Server

note over Job: Start job close routine.
note over Job, "Execution\nPlatform": Job is removed from Active Jobs Store.\nFrom the perspective of API it does not\nmatter what happens to the cloud job.

deactivate "Execution\nPlatform"

Job -> Storage: Write logs
deactivate Job


User -> Server: Request dismiss after job is finished
activate Server
Server -> Job: Check job is active
Job --> Server: Job is inactive
Server --> User: Respond with 404
deactivate Server

@enduml
