version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./api
      target: dev
    ports:
      - '5050:5050'
    env_file:
      - .env
    volumes:
      - ./api:/app
      - ./.data/api:/.data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - process_api_net

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z.fips
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./.data/minio:/data
    networks:
      - process_api_net

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.18
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - process_api_net

networks:
  process_api_net:
    external: true
