version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./api
      target: dev
    ports:
      - '5050:5050'
    env_file:
      - .env
    volumes:
      - ./api:/app
      - ./.data:/.data
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
