version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - '80:5050'
    env_file:
      - .env
    volumes:
      - ./plugins:/app/plugins
      - ./.data/api:/.data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - process_api_net
    depends_on:
      - minio

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z.fips
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./.data/minio:/data
    networks:
      - process_api_net

networks:
  process_api_net:
    external: true
