basePath: /
definitions:
  jobs.Info:
    properties:
      description:
        type: string
      id:
        type: string
      jobControlOptions:
        items:
          type: string
        type: array
      outputTransmission:
        items:
          type: string
        type: array
      title:
        type: string
      version:
        type: string
    type: object
  jobs.Input:
    properties:
      literalDataDomain:
        $ref: '#/definitions/jobs.LiteralDataDomain'
    type: object
  jobs.Inputs:
    properties:
      id:
        type: string
      input:
        $ref: '#/definitions/jobs.Input'
      maxOccurs:
        type: integer
      minOccurs:
        type: integer
      title:
        type: string
    type: object
  jobs.JobLogs:
    properties:
      api_log:
        items:
          type: string
        type: array
      container_log:
        items:
          type: string
        type: array
    type: object
  jobs.jobStatus:
    properties:
      commands:
        items:
          type: string
        type: array
      jobID:
        type: string
      processID:
        type: string
      status:
        type: string
      type:
        default: process
        type: string
      updated:
        type: string
    type: object
  jobs.Link:
    properties:
      href:
        type: string
      rel:
        type: string
      title:
        type: string
      type:
        type: string
    type: object
  jobs.LiteralDataDomain:
    properties:
      dataType:
        type: string
      valueDefinition:
        $ref: '#/definitions/jobs.ValueDefinition'
    type: object
  jobs.Output:
    properties:
      formats:
        items:
          type: string
        type: array
    type: object
  jobs.Outputs:
    properties:
      id:
        type: string
      inputID:
        description: json omit
        type: string
      output:
        $ref: '#/definitions/jobs.Output'
      title:
        type: string
    type: object
  jobs.ProcessDescription:
    properties:
      info:
        $ref: '#/definitions/jobs.Info'
      inputs:
        items:
          $ref: '#/definitions/jobs.Inputs'
        type: array
      links:
        items:
          $ref: '#/definitions/jobs.Link'
        type: array
      outputs:
        items:
          $ref: '#/definitions/jobs.Outputs'
        type: array
    type: object
  jobs.ValueDefinition:
    properties:
      anyValue:
        type: boolean
      possibleValues:
        items:
          type: string
        type: array
    type: object
  jobs.jobResponse:
    properties:
      jobID:
        type: string
      message:
        type: string
      outputs: {}
      processID:
        type: string
      status:
        type: string
      type:
        default: process
        type: string
      updated:
        type: string
    type: object
externalDocs:
  description: Schemas
  url: http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/
host: http://vap.api.dewberryanalytics.com
info:
  contact:
    email: slawler@dewberry.com
    name: Seth Lawler
  description: An OGC compliant process server.
  title: Process-API Server
  version: dev-4.19.23
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: '[LandingPage Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_landing_page)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Landing Page
      tags:
      - info
  /conformance:
    get:
      consumes:
      - '*/*'
      description: '[Conformance Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_conformance_classes)'
      produces:
      - application/json
      responses:
        "200":
          description: conformsTo:["http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/...."]
          schema:
            additionalProperties: true
            type: object
      summary: API Conformance List
      tags:
      - info
  /jobs:
    get:
      consumes:
      - '*/*'
      description: '[Job List Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_job_results)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/jobs.jobStatus'
            type: array
      summary: Summary of all (cached) Jobs
      tags:
      - jobs
  /jobs/{jobID}:
    delete:
      consumes:
      - '*/*'
      description: '[Dismss Job Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#ats_dismiss)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs.jobResponse'
      summary: Dismiss Job
      tags:
      - jobs
    get:
      consumes:
      - '*/*'
      description: '[Job Results Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_job_results)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs.jobResponse'
      summary: Job Results
      tags:
      - jobs
  /jobs/{jobID}/logs:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs.JobLogs'
      summary: Job Logs
      tags:
      - jobs
  /processes:
    get:
      consumes:
      - '*/*'
      description: '[Process List Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_list)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/jobs.Info'
            type: array
      summary: List Available Processes
      tags:
      - processes
  /processes/{processID}:
    get:
      consumes:
      - '*/*'
      description: '[Process Description Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_description)'
      parameters:
      - description: processID
        in: path
        name: processID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs.ProcessDescription'
      summary: Describe Process Information
      tags:
      - processes
  /processes/{processID}/execution:
    post:
      consumes:
      - '*/*'
      description: '[Execute Process Specification](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_create_job)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs.jobResponse'
      summary: Execute Process
      tags:
      - processes
schemes:
- http
swagger: "2.0"
