name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create bucket
        run: |
          docker run \
            minio/mc:RELEASE.2023-08-18T21-57-55Z

