name: Update Sequence Diagrams Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'imgs/umls/sequence-diagrams/*.puml'
  workflow_dispatch:

jobs:
  update-squence-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install plantuml==0.3.0
        pip install six==1.14.0

    - name: Generate URLs using the Python script
      run: python3 imgs/umls/sequence-diagrams/create_wiki.py

    - name: Push changes
      run: |
        git clone https://github.com/${{ github.repository }}.wiki.git
        mv Sequence-Diagrams.md ./process-api.wiki/
        cd ./process-api.wiki
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        # Reference the commit hash from the main repo in the commit message
        git commit -m "Update Sequence diagrams based on commit ${{ github.sha }}"
        git remote set-url origin https://x-access-token:${{ github.token }}@github.com/Dewberry/process-api.wiki.git
        git push